[package]
name = "DogeHealth"
version = "0.0.1"
authors = ["anonymous"]

{source = { local = "/Users/macbook/move-stdlib/language/move-stdlib" }

[addresses]
DogeHealth = "0x9c643a5f2a21099e0386ca34369a8e55789d841754a74c12eebc009c4fb2e286"

