[package]
name = "DogeHealth"
version = "0.0.1"
authors = ["anonymous"]
license = "Apache-2.0"

[dependencies]
MoveStdlib = { local = "/Users/macbook/move-stdlib/language/move-stdlib" }

[addresses]
private_wallet = '0x5497a18f7b130137ab0eddc145a2ca8f0e9ad5f33a01351016251aedbafb25fb'
