[package]
name = "DogeHealth"
authors = ["anonymous"]
license = "Apache-2.0"

[dependencies]
MoveStdlib = { path = "../../move-stdlib/language/move-stdlib" }

[addresses]
private_wallet = 
"0x5497a18f7b130137ab0eddc145a2ca8f0e9ad5f33a01351016251aedbaf25fb"
public_wallet = 
"0x9c643a5f2a21099e0386ca34369a8e55789d841754a74c12eebc009c4fb2e286"
}

